### ISSUE TITLE
Question in terms of AmountT

### ISSUE THREAD

**Issue by jbbjarnason** [mamrhein/quantities.rs#16] opened 2024-08-23 10:13 UTC
Coming from cpp using `mp-units` https://github.com/mpusz/mp-units the quantity amount type was templated on quantity level, so each instance of quantity could adjust its representative type, in your library AmountT.

For reference, from their cpp code
```cpp
template<Reference auto R, RepresentationOf<get_quantity_spec(R).character> Rep = double>
class quantity ...
```

As far as I understand your library the AmountT is globally set, so for different units the same AmountT is used.

Was this a design decision made to begin with or is this something that could be defined on `trait Quantity` level? 
Or am I misunderstanding the whole thing.

**Comment by mamrhein** [comment] 2024-08-25 06:52
This is "by design" just because I can't think of an use case where you need different numeric types for different quantities.
Do you have such a use case?

**Comment by jbbjarnason** [comment] 2024-08-26 19:10
Previously in cpp, we had typed inter process communication abstraction with support for Voltage, Current, Temperature etc. 
Everything was transported as signed integer with fixed precision, but in business logic it was often useful to use double for different business logic.

**Comment by mamrhein** [comment] 2024-08-27 10:45
Why did you choose different numeric types for "transport" and business logic?

**Comment by jbbjarnason** [comment] 2024-08-28 12:35
Only because I could have full control of signed integers with fixed precision to for nano meter or such, so I would control rounding and truncating fully before transmit.

This is not a hard requirement on my side so I can change the cpp code to double and use double then on everything.

This issue can be closed.

**Comment by mamrhein** [comment] 2024-08-28 12:37
Ok. Closing this issue.

**Closed by mamrhein** 2024-08-28 12:37 UTC

**Comment by mamrhein** [comment] 2024-09-30 09:37
I'm not sure whether I do understand what would be required here.
To support different types for the numeric part of a quantity would mean to make AmountT a type parameter of each quantity struct. This would definitely be a breaking change. 
So, I'd like to avoid that unless there is a very strong demand.
